language: go

go:
  - "1.10"

sudo: required

services:
  - docker

script:
- make check
- make test
- make build

deploy:
  provider: script
  script: make push
  on:
    branch: master
    tags: true
